server:
  port: 20030
spring:
  jpa:
    open-in-view: false
  data:
    mongodb:
      database: funds
      host: 192.168.1.10
      port: 30005
  http:
    multipart:
shellshellfish:
  asset-alloction-url: "http://192.168.1.10:20020"
  userinfo-url: "http://192.168.1.10:20060"

grpc:
  asset-allocation:
    host: localhost
    port: 20021

management:
  endpoints:
    web:
      base-path: /