server:
  port: 10031
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  data:
    mongodb:
      database: test1
      host: 192.168.1.10
      port: 27017
  rabbitmq:
    username: ssf
    password: shellshellfish
    host: 192.168.1.22
    port: 5672
    virtual-host: aaas
    topicQueuePayName: com.ssf.topic.queue.pay
    topicQueueOrderName: com.ssf.topic.queue.order
    topicQueueTrdLogName: com.ssf.topic.queue.trdlog
    topicQueueBankcardName: com.ssf.topic.queue.bankcard
    topicExchangeName: com.ssf.topic.exchange
    topicPay: shellshellfish.pay
    topicOrder: shellshellfish.order
    data:
        mongodb:
            host: 192.168.1.10
            port: 27017
            database: zhongzheng


datasource:
  sampleapp:
    url: jdbc:mysql://192.168.1.10:3306/ssftrdpay?useUnicode=true&connectionCollation=utf8_general_ci&characterSet=utf8&characterEncoding=utf-8
    username: sa
    password: 1qaz@WSX
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: ssftrdpay
    maxPoolSize: 20
    hibernate:
      connection:
        useUnicode: true
        characterEncoding: UTF-8
      jdbc:
        batch_size: 50
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

grpc:
  finance_prod_client:
    host: localhost
    port: 10030
using:
  spring:
    schedulerFactory: true
org:
  quartz:
    jobStore:
        class: org.quartz.simpl.RAMJobStore
        misfireThreshold: 60000
    threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 2
        threadsInheritContextClassLoaderOfInitializingThread: true
cron:
  frequency:
  #每天17：30分开始
    jobwithcrontrigger: 0 45 17 ? * * *