---
server:
  port: 10030
  contextPath: /
spring:
  data:
      mongodb:
        database: funds
        host: localhost
        port: 27017
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/ssftrdorder?useUnicode=true&characterEncoding=utf-8
    username: sa
    password: 1qaz@WSX
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

grpc:
  host: localhost
  port: 10031