spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false 
            
            application:
        name: ssf-risk-assessment
    profiles:
        active: dev

    jackson:
      serialization:
        fail-on-empty-beans: false


