spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false 
            
            application:
        name: ssf-risk-assessment

    jackson:
      serialization:
        fail-on-empty-beans: false

    data:
        mongodb:
            host: 192.168.1.10
            port: 27017
            database: test

server:
    port: 8088
    
    
application:
    swagger:
        title: tplatform API
        description: tplatform API documentation
        version: 0.1.X
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
        
    cors: 
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS, HEAD
        allowed-headers: "*"
        exposed-headers: X-Total-Count, Link
        allow-credentials: true
        max-age: 1800

    