version: "2"


services:
  aaas-app-oeminfo:
    image: aaas-app-oeminfo:latest
    labels:
      - "aaas-app-oeminfo"
    ports:
      - "10060:10060"
      - "10061:10061"
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - _JAVA_OPTIONS=-Xmx256m
      
      
      
