spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false 
            
            application:
        name: ssf-finance
    profiles:
        active: dev

    jackson:
      serialization:
        fail-on-empty-beans: false


shellshellfish:
   asset-allocation-url: "http://localhost:10020"
