---
server:
  port: 8080
  contextPath: /
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
#    url: jdbc:mysql://192.168.0.25:3306/websystique
#    username: myuser
#    password: mypassword
    url: jdbc:mysql://192.168.0.33:3306/ssfuser
    username: sa
    password: abcd1234

    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: ssfuser
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

