server:
  port: 10031
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  rabbitmq:
    username: ssf
    password: shellshellfish
    host: 192.168.1.22
    port: 5672
    virtual-host: aaas
    topicQueueName: com.ssf.topic.queue
    topicExchangeName: com.ssf.topic.exchange


datasource:
  sampleapp:
    hibernate:
      connection:
        useUnicode: true
        characterEncoding: UTF-8
      jdbc:
        batch_size: 50
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

grpc:
  finance_prod_client:
    host: localhost
    port: 10030