zuul:
  routes:
    userinfo:
      path: /api/userinfo/**
      url: http://192.168.1.3:10021/api/userinfo/
    userlogin:
      path: /api/useraccount/**
      url: http://localhost:10020/api/useraccount/
    riskassessments:
      path: /api/riskassessments/**
      url: http://localhost:10022/api/riskassessments/
#    accounts:
#      path: /v1/accounts/**
#      url: http://localhost:8080/api/accounts
#    bankaccounts:
#      path: /v1/bankaccounts/**
#      url: forward:/api/bankaccounts/**
    auth:
      path: /v1/auth/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://localhost:8001/auth

ribbon:
  eureka:
    enabled: false

server:
  port: 10024
 
security:
  oauth2: 
    resource:
      userInfoUri: http://localhost:10025/auth/user
      
shellshellfish:
  ignoredWhitelist:
    - /api/userinfo/**
    - /api/useraccount/**
    - /v1/auth/oauth/token
    - /v1/api/bankaccounts/**
  