zuul:
  routes:
    accounts:
      path: /v1/accounts/**
      url: http://localhost:8080/api/accounts
    bankaccounts: 
      path: /v1/bankaccounts/**
      url: forward:/api/bankaccounts/**
    auth:
      path: /v1/auth/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://localhost:8001/auth

ribbon:
  eureka:
    enabled: false

server:
  port: 8000
 
security:
  oauth2: 
    resource:
      userInfoUri: http://localhost:8001/auth/user
      
shellshellfish:
  ignoredWhitelist:
    - /v1/auth/oauth/token
    - /v1/api/bankaccounts/**
  