zuul:
  routes:
    api-mid:
      path: /phoneapi-ssf/**
      url: http://localhost:10025/phoneapi-ssf
    userinfo:
      path: /api/userinfo/**
      url: http://localhost:10021/api/userinfo/
    userinfo-swagger:
      path: /api/userinfo/swagger-ui.html
      url: http://localhost:10021/swagger-ui.html#
    userlogin:
      path: /api/useraccount/**
      url: http://localhost:10020/api/useraccount/
    userlogin-swagger:
      path: /api/useraccount/swagger-ui.html/**
      url: http://localhost:10020/swagger-ui.html
    riskassessments:
      path: /api/riskassessments/**
      url: http://localhost:10022/api/riskassessments/
    riskassessments-swagger:
      path: /api/riskassessments/swagger-ui.html/**
      url: http://localhost:10022/swagger-ui.html/
#    accounts:
#      path: /v1/accounts/**
#      url: http://localhost:8080/api/accounts
#    bankaccounts:
#      path: /v1/bankaccounts/**
#      url: forward:/api/bankaccounts/**
    auth:
      path: /v1/auth/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://localhost:8001/auth

ribbon:
  eureka:
    enabled: false

server:
  port: 10024
 
security:
  oauth2: 
    resource:
      userInfoUri: http://localhost:10025/auth/user
      
shellshellfish:
  ignoredWhitelist:
    - /phoneapi-ssf/**
    - /api/userinfo/**
    - /api/useraccount/**
    - /api/riskassessments/**
    - /v1/auth/oauth/token
    - /v1/api/bankaccounts/**
  