---
server:
  port: 10070
  contextPath: /
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:

datasource:
  sampleapp:
    url: jdbc:mysql://192.168.1.10:3306/ssflogin?useUnicode=true&characterEncoding=utf-8
    username: sa
    password: 1qaz@WSX
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
grpc:
  host: 192.168.1.10
  port: 10071
ali:
    accessKeyId: LTAIpZL9r6q0kkPV
    accessKeySecret: dBsex06RIIB7LfBF2Pdx4TeRzpklwr
app:
    debug: true
redis:
    host: 192.168.1.10
    port: 6379
    pwd: redis123
sms:
    signcode: SMS_110225054
    signname: \u8D22\u5BCCE\u667A\u6295