server:
  port: 10020
mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      password: t5MqqozQDNramNHh
      url: jdbc:mysql://192.168.1.10:3306/choice?useUnicode=true&characterEncoding=utf-8
      username: ssf08

#        password: uCIPzdEJzbeoFAMj
#        url: jdbc:mysql://192.168.1.10:3306/choicecopy?useUnicode=true&characterEncoding=utf-8
#        username: ssf09

#      password: 1xtZgrp#XzxGi$3OZ
#      url: jdbc:mysql://192.168.1.15:3306/choicedebug?autoReconnect=true&allowMultiQueries=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=utf-8
#      username: ssf0015
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: funds
      host: 192.168.1.10
      port: 27017
      collection: portfolio_yield_all
grpc:
  host: localhost
  port: 10021
  daily-fund-client:
    host: localhost
    port: 10091

application:
    swagger:
        title: SSF Platform API
        description: Shell shell fish API documentation
        version: 0.1.X
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl: