mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 1qaz@WSX
        url: jdbc:mysql://localhost:3306/choice?useUnicode=true&characterEncoding=utf-8
        username: sa