server:
  port: 10020
mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: R489cfRKfEY7LNM9
        url: jdbc:mysql://192.168.1.249:3306/choice?useUnicode=true&characterEncoding=utf-8
        username: ssf01
    jpa:
      hibernate:
        ddl-auto: update
grpc:
  host: localhost
  port: 10021
  daily-fund-client:
    host: localhost
    port: 10091

application:
    swagger:
        title: SSF Platform API
        description: Shell shell fish API documentation
        version: 0.1.X
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl: